version: 2

sources:
  - name: brooklyndata
    database: pipedreams
    schema: raw
    tables:
      - name: olist_geolocation_dataset
        columns:
          - name: geolocation_zip_code_prefix
            tests:
              - not_null
      - name: olist_order_customer_dataset
        columns:
          - name: customer_id
            tests:
              - unique
              - not_null
      - name: olist_order_items_dataset
        columns:
          - name: order_id
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null
          - name: seller_id
            tests:
              - not_null
      - name: olist_order_payments_dataset
        columns:
          - name: order_id
            tests:
              - not_null
      - name: olist_order_reviews_dataset
        columns:
          - name: review_id
            tests:
              - not_null
          - name: order_id
            tests:
              - not_null
      - name: olist_orders_dataset
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
          - name: customer_id
            tests:
              - not_null
      - name: olist_products_dataset
        columns:
          - name: product_id
            tests:
              - unique
              - not_null
      - name: olist_sellers_dataset      
        columns:
          - name: seller_id
            tests:
              - unique
              - not_null
