name: 'pipedreams_de_task'
version: '1.0.0'
config-version: 2

profile: 'pipedreams_de_task'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:       
  - "target"
  - "dbt_packages"


models:
  pipedreams_de_task:
    # Config indicated by + and applies to all files under models/example/
    brooklyndata:
      +materialized: view

tests:
  +store_failures: true